#!/usr/bin/env sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
	echo "Running lint and format checks before merge into main..."
	pnpm run check
	pnpm run check-types
fi
